### PR TITLE
Title changed.

### PR DESCRIPTION
**Pull request by inbarajan0805**
Hi Nivedini, please accept this change.

### CODE REVIEW

**Review by Nivedini — CHANGES_REQUESTED** [review]
change it to "Angular2 Demo"

**Review by inbarajan0805 — COMMENTED** [review]
updated title to angular2 demo

**Review by Nivedini — APPROVED** [review]
Approved

**Comment by Nivedini** [comment]
closing this pull request

**Comment by Nivedini** [comment]
reopening the pull request

**Pull request merged**
